name: Publish to PyPi
on:
  release:
    types: [published]
  # Enables running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Install EE and dependencies
        run: |
          pip install ./python[tests]
      - name: Smoke test
        run: >
          python -c 'import ee;
          import json;
          import os;
          from google.auth import identity_pool;
          from google.auth import transport;

          scopes = [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/earthengine",
          ];
          path = os.environ["GOOGLE_APPLICATION_CREDENTIALS"];
          info = json.load(open(path));
          credentials = identity_pool.Credentials.from_info(info).with_scopes(scopes);
          print(credentials.quota_project_id);
          print(credentials.project_number);
          request = transport.Request();
          print(credentials.get_project_id(request));
          ee.Initialize(credentials);

          print(ee.Image("srtm90_v4").getInfo())'
